///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OptikModel {
/*
{
  "student_id": "0313426879",
  "all_correct": [
    4
  ],
  "all_wrong": [
    1
  ],
  "all_empty": [
    21
  ],
  "total_score": 0,
  "raw_ans_file": "static/opticsPhotos/rawFiles/1705355083820286.jpg",
  "final_ans_file": "static/opticsPhotos/finalFiles/0313426879.jpg"
} 
*/

  String? studentId;
  List<int?>? allCorrect;
  List<int?>? allWrong;
  List<int?>? allEmpty;
  int? totalScore;
  String? rawAnsFile;
  String? finalAnsFile;

  OptikModel({
    this.studentId,
    this.allCorrect,
    this.allWrong,
    this.allEmpty,
    this.totalScore,
    this.rawAnsFile,
    this.finalAnsFile,
  });
  OptikModel.fromJson(Map<String, dynamic> json) {
    studentId = json['student_id']?.toString();
    if (json['all_correct'] != null) {
      final v = json['all_correct'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      allCorrect = arr0;
    }
    if (json['all_wrong'] != null) {
      final v = json['all_wrong'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      allWrong = arr0;
    }
    if (json['all_empty'] != null) {
      final v = json['all_empty'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      allEmpty = arr0;
    }
    totalScore = json['total_score']?.toInt();
    rawAnsFile = json['raw_ans_file']?.toString();
    finalAnsFile = json['final_ans_file']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['student_id'] = studentId;
    if (allCorrect != null) {
      final v = allCorrect;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['all_correct'] = arr0;
    }
    if (allWrong != null) {
      final v = allWrong;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['all_wrong'] = arr0;
    }
    if (allEmpty != null) {
      final v = allEmpty;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['all_empty'] = arr0;
    }
    data['total_score'] = totalScore;
    data['raw_ans_file'] = rawAnsFile;
    data['final_ans_file'] = finalAnsFile;
    return data;
  }
}
